[General]
description=Calls a native GCC compiler
display_name=This Machine
extensions=C Sources (*.c *.h)
manual=targets/gcc/manual/gccmanual.html
name=gcc
template=targets/gcc/template.c

[Target]
cflags=-arch i386 -arch ppc -Wimplicit
include_dirs=targets/gcc/include
lflags=-arch i386 -arch ppc -lGLee -lkiss -lpthread -lm -lglfw -framework AGL -framework OpenGL -framework Carbon
lib_dirs=targets/gcc/lib
