######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 8 17:15:46 2009
######################################################################

include(../../config.pri)

TEMPLATE = lib
TARGET = 
DEPENDPATH += src
INCLUDEPATH += ../../external/include ../kiss/include

CONFIG -= qt debug debug_and_release
CONFIG += staticlib release

# Input
SOURCES += src/stub.c \
           
QMAKE_CLEAN += src/*~ libkiss_sim.a

